### PR TITLE
Liquid qt support

### PR DESCRIPTION
**Pull request by greenaddress**
This adds liquid qt support

Tested on:

-  OSX retina and non-retina
-  Linux Ubuntu and Debian
-  Windows 10

### CODE REVIEW

**Comment by instagibbs** [comment]
concept ACK!

**Comment by instagibbs** [comment]
```
/bin/sed -e 's:\(res\/\(icons\|movies\)/\):/home/greg/bitcoin-dev/liquid/src/qt/\1:' <"qt/bitcoin.qrc" >"qt/qrc_bitcoin_build.qrc"
  GEN      qt/moc_walletview.cpp
make[2]: *** No rule to make target 'qt/res/rendered_icons/about.png', needed by 'qt/qrc_bitcoin.cpp'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/greg/bitcoin-dev/liquid/src'
Makefile:9626: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/greg/bitcoin-dev/liquid/src'
Makefile:688: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by greenaddress** [comment]
probably local qt setup, please try under gitian with gitian runners configured with the latest descriptors.

**Comment by greenaddress** [comment]
merged in liquid.3.14.1 branch

**Pull request closed without merging**
