### PR TITLE
Fix progress reporting & initialblockdownload

### PR DESCRIPTION
**Pull request by stevenroose**
depends on #9

Both the debug log and `getblockchaininfo` were showing `progress=1` always.

This PR replaces Core's chain statistics-based estimation with simple block-based estimation because are dealing with fixed-interval blocks.

Also implements the `initialblockdownload` value in `getblockchaininfo` based on the same heuristic.

### CODE REVIEW

**Comment by instagibbs** [comment]
should be easy to test via `-con_npowtargetspacing`, right? Set a 1 second interval, wait 5(?) seconds, see if progress goes down.

Does this need port to elements?

**Comment by stevenroose** [comment]
@instagibbs Updated PR to use `nPowTargetSpacing`, thanks.

**Comment by instagibbs** [comment]
I'd really like a functional test for this since it's touching a number of internals I haven't touched before

**Comment by instagibbs** [comment]
utACK, waiting on travis

**Pull request merged**
