### PR TITLE
Blockstream - don't care about that. 

### PR DESCRIPTION
**Pull request by EvertonMelo**
was discovered in ZeroMQ libzmq (aka 0MQ) 4.2.x and 4.3.x before 4.3.1. A v2_decoder.cpp zmq::v2_decoder_t::size_ready integer overflow allows an authenticated attacker to overwrite an arbitrary amount of bytes beyond the bounds of a buffer, which can be leveraged to run arbitrary code on the target system.

### CODE REVIEW

**Comment by EvertonMelo** [comment]
@greenaddress @instagibbs @alessandro-saglimbeni 

hi, can help me?

I send email for thist vulnerabilities but I was not answered, can you tell me if you are interested or not in this correction?

**Comment by instagibbs** [comment]
this entire repo is deprecated, and should not be used. Instead use the Elements repo. Leaving this open to make sure people know(further) that there are remaining issues unresolved.

**Comment by EvertonMelo** [comment]
@instagibbs 
grateful for the return.

**Comment by instagibbs** [comment]
appreciate the report

**Comment by EvertonMelo** [comment]
arrombadoscretinos

**Pull request closed without merging**
