### PR TITLE
validation: change pindexPrev->nHeight + 1 to nHeight

### PR DESCRIPTION
**Pull request by shafisher**
validation: change pindexPrev->nHeight + 1 to nHeight

### CODE REVIEW

**Comment by instagibbs** [comment]
nice catch, we shouldn't hit this anyways but bad idea what we're doing.

**Comment by instagibbs** [comment]
utACK

**Comment by shafisher** [comment]
Code rebased to make clear what we're doing.

**Comment by stevenroose** [comment]
utACK, wonder why that permissive NULL check was there, though..

**Comment by instagibbs** [comment]
Genesis block. We don't validate the Genesis block though.

**Comment by instagibbs** [comment]
re-utACK, I'm going to cherry-pick this against elements as a forward port to run it through travis

**Comment by instagibbs** [comment]
https://github.com/ElementsProject/elements/pull/464 awaiting travis run here

**Comment by instagibbs** [comment]
Passed.

**Pull request merged**
