### PR TITLE
Validation: stop logging fake pow data

### PR DESCRIPTION
**Pull request by Sjors**
Same reason as 3dc836a4acb7bbf28e11e5746a72af3ee858f4ba

Before:
schermafbeelding 2018-11-29 om 12 03 18

After:
schermafbeelding 2018-11-29 om 12 03 02

### CODE REVIEW

**Comment by instagibbs** [comment]
This will need upstreaming to elements

**Comment by instagibbs** [comment]
and cherry-picking to https://github.com/ElementsProject/elements/pull/452 for rebase

**Comment by stevenroose** [comment]
utACK

**Comment by instagibbs** [comment]
utACK

**Pull request merged**
